#ifndef _WINERROR_
#define _WINERROR_

#define ERROR_DEVICE_NOT_CONNECTED 0x48F
#define ERROR_INVALID_HANDLE 0x6
#define ERROR_INVALID_HANDLE_STATE 1609
#define ERROR_ALREADY_EXISTS 183

#endif //_WINERROR_
